export const SKILLS = [
    { tech: "React", icon: "devicon-react-original" },
    { tech: "Next", icon: "devicon-nextjs-plain" },
    { tech: "Expo", icon: "devicon-react-original" },
    { tech: "Django", icon: "devicon-django-plain" },
    { tech: "Express", icon: "devicon-express-original" },
    { tech: "Node", icon: "devicon-nodejs-plain" },
    { tech: "Bun", icon: "devicon-bun-plain" },
    { tech: "PostgreSQL", icon: "devicon-postgresql-plain" },
    { tech: "MongoDB", icon: "devicon-mongodb-plain" },
    { tech: "Redis", icon: "devicon-redis-plain" },
    { tech: "Prisma", icon: "devicon-prisma-original" },
    { tech: "Zustand", icon: "devicon-react-original" },
    { tech: "Tanstack Query", icon: "devicon-react-original" },
    { tech: "Postman", icon: "devicon-postman-plain" },
    { tech: "Tailwind", icon: "devicon-tailwindcss-plain" },
    { tech: "shadcn", icon: "devicon-react-original" },
    { tech: "Motion", icon: "devicon-framer-original" },
    { tech: "GSAP", icon: "devicon-greensock-plain" },
    { tech: "JavaScript", icon: "devicon-javascript-plain" },
    { tech: "TypeScript", icon: "devicon-typescript-plain" },
    { tech: "Python", icon: "devicon-python-plain" },
    { tech: "C/C++", icon: "devicon-cplusplus-plain" },
    { tech: "SQL", icon: "devicon-azuresqldatabase-plain" },
    { tech: "Git", icon: "devicon-git-plain" },
    { tech: "Github", icon: "devicon-github-original" },
    { tech: "Figma", icon: "devicon-figma-plain" },
    { tech: "Docker", icon: "devicon-docker-plain" },
    { tech: "Linux", icon: "devicon-linux-plain" },
];
